// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoAgenda.Models;

namespace ProjetoAgenda.Migrations
{
    [DbContext(typeof(ArmazenamentoWebContext))]
    partial class ArmazenamentoWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ProjetoAgenda.Models.GrupoModel", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("IdGrupo");

                    b.ToTable("Grupo");
                });

            modelBuilder.Entity("ProjetoAgenda.UsuarioModel", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdGrupo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("grupoIdGrupo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUsuario");

                    b.HasIndex("grupoIdGrupo");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProjetoAgenda.UsuarioModel", b =>
                {
                    b.HasOne("ProjetoAgenda.Models.GrupoModel", "grupo")
                        .WithMany()
                        .HasForeignKey("grupoIdGrupo");

                    b.Navigation("grupo");
                });
#pragma warning restore 612, 618
        }
    }
}
